#!/bin/bash
# python scripts/run_single_skill_from_skills_sh.py --db crawling/skills/all_skills/by_platform/skillsdirectory.db --repos-root /media/szk/skills_directory --output-dir /home/szk/result/skills_directory --intermediate-dir /home/szk/result/skills_directory/hdd_intermediate --pipeline-stage prepare --scan-workers 6 --format json,csv
# python scripts/run_single_skill_from_skills_sh.py --db crawling/skills/all_skills/by_platform/clawhub.db --repos-root /media/szk/clawhub --output-dir /home/szk/result/clawhub --intermediate-dir /home/szk/result/clawhub/hdd_intermediate --pipeline-stage prepare --scan-workers 6 --format json,csv
# python scripts/run_single_skill_from_skills_sh.py --db crawling/skills/all_skills/by_platform/skillsmp.db --repos-root /media/szk/skills_mp_2 --output-dir /home/szk/result/skillsmp --intermediate-dir /home/szk/result/skillsmp/hdd_intermediate --pipeline-stage prepare --scan-workers 6 --format json,csv
# python scripts/run_single_skill_from_skills_sh.py --db crawling/skills/all_skills/by_platform/lobehub.db --repos-root /media/szk/lobehub --output-dir /home/szk/result/lobehub --intermediate-dir /home/szk/result/lobehub/hdd_intermediate --pipeline-stage prepare --scan-workers 6 --format json,csv
# python scripts/run_single_skill_from_skills_sh.py --repos-root /media/szk/clawhub --output-dir /home/szk/result/clawhub --intermediate-dir /home/szk/result/clawhub/hdd_intermediate_2 --pipeline-stage prepare --scan-workers 6 --format json,csv
# python scripts/run_single_skill_from_skills_sh.py --repos-root /media/szk/skills_mp_2 --output-dir /home/szk/result/skillsmp --intermediate-dir /home/szk/result/skillsmp/hdd_intermediate_2 --pipeline-stage prepare --scan-workers 6 --format json,csv
python scripts/run_single_skill_from_skills_sh.py  --repos-root /media/szk/skills_directory --db crawling/skills/all_skills/by_platform/skillsdirectory.db --output-dir /home/szk/result/skills_directory --intermediate-dir /home/szk/result/skills_directory/hdd_intermediate --pipeline-stage review --llm-workers 14 --llm-review-mode review  --llm-provider openai --format json,csv
python scripts/run_single_skill_from_skills_sh.py  --repos-root /media/szk/clawhub --output-dir /home/szk/result/clawhub --intermediate-dir /home/szk/result/clawhub/hdd_intermediate --pipeline-stage review --llm-workers 14 --llm-review-mode review  --llm-provider openai --format json,csv
python scripts/run_single_skill_from_skills_sh.py  --repos-root /media/szk/skills_mp_2 --output-dir /home/szk/result/skillsmp --intermediate-dir /home/szk/result/skillsmp/hdd_intermediate --pipeline-stage review --llm-workers 14 --llm-review-mode review  --llm-provider openai --format json,csv
python scripts/run_single_skill_from_skills_sh.py  --repos-root /media/szk/lobehub --db crawling/skills/all_skills/by_platform/lobehub.db --output-dir /home/szk/result/lobehub --intermediate-dir /home/szk/result/lobehub/hdd_intermediate --pipeline-stage review --llm-workers 14 --llm-review-mode review  --llm-provider openai --format json,csv